complexity:
  TooManyFunctions:
    ignorePrivate: true

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

comments:
  CommentOverPrivateProperty:
    active: false
  CommentOverPrivateFunction:
    active: false
  EndOfSentenceFormat:
    active: true
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true

style:
  UnnecessaryParentheses:
    active: false
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  UseIfInsteadOfWhen:
    active: true
  ExpressionBodySyntax:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true

  # Numbers are used for enums and blur algorithms matrices
  MagicNumber:
    ignoreNumbers: ['-1', '0', '1',
                    # numbers for enums
                    '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
                    # numbers for degrees and percentages in progress and shape algorithms
                    '-90', '90', '100', '-180', '180', '-270', '270', '360', '3.6', '0.75']

naming:
  PackageNaming:
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9_]*)*'
  FunctionMaxLength:
    active: false

formatting:
  # We already have MaxLineLength from detekt, which is suppressed in few cases. This rule cannot be suppressed with annotations
  MaximumLineLength:
    active: false
  MultiLineIfElse:
    active: true
    autoCorrect: true
  NoEmptyFirstLineInMethodBlock:
    active: true
    autoCorrect: true
  SpacingBetweenDeclarationsWithComments:
    active: true
    autoCorrect: true
  ArgumentListWrapping:
    active: true
    autoCorrect: false
  NoUnusedImports:
    active: true
    autoCorrect: true

