name: Publish to mavenCentral
          
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Create gpg file
        run:
          echo "${{ secrets.SONATYPE_GPG_CONTENT }}" | base64 -d > "${{ secrets.SONATYPE_GPG_PATH }}"
        shell: bash
      - name: Build and publish
        run: |
          ./gradlew build
          SONATYPE_USER="${{ secrets.SONATYPE_USER }}" SONATYPE_PWD="${{ secrets.SONATYPE_PWD }}" SONATYPE_GPG_KEY="${{ secrets.SONATYPE_GPG_KEY }}" SONATYPE_GPG_PWD="${{ secrets.SONATYPE_GPG_PWD }}" SONATYPE_GPG_PATH="${{ secrets.SONATYPE_GPG_PATH }}" ./gradlew publish
      - name: Cleanup
        run:
          bash rm -f "${{ secrets.SONATYPE_GPG_PATH }}"
